[bits 32]


extern tramplin_0
extern tramplin_1
extern tramplin_2
extern tramplin_3
extern tramplin_4
extern tramplin_5
extern tramplin_6
extern tramplin_7
extern tramplin_8
extern tramplin_9
extern tramplin_a
extern tramplin_b
extern tramplin_c
extern tramplin_d
extern tramplin_e
extern tramplin_f
extern tramplin_10
extern tramplin_11
extern tramplin_12
extern tramplin_13
extern tramplin_14
extern tramplin_15
extern tramplin_16
extern tramplin_17
extern tramplin_18
extern tramplin_19
extern tramplin_1a
extern tramplin_1b
extern tramplin_1c
extern tramplin_1d
extern tramplin_1e
extern tramplin_1f
extern tramplin_20
extern tramplin_21
extern tramplin_22
extern tramplin_23
extern tramplin_24
extern tramplin_25
extern tramplin_26
extern tramplin_27
extern tramplin_28
extern tramplin_29
extern tramplin_2a
extern tramplin_2b
extern tramplin_2c
extern tramplin_2d
extern tramplin_2e
extern tramplin_2f
extern tramplin_30
extern tramplin_31
extern tramplin_32
extern tramplin_33
extern tramplin_34
extern tramplin_35
extern tramplin_36
extern tramplin_37
extern tramplin_38
extern tramplin_39
extern tramplin_3a
extern tramplin_3b
extern tramplin_3c
extern tramplin_3d
extern tramplin_3e
extern tramplin_3f
extern tramplin_40
extern tramplin_41
extern tramplin_42
extern tramplin_43
extern tramplin_44
extern tramplin_45
extern tramplin_46
extern tramplin_47
extern tramplin_48
extern tramplin_49
extern tramplin_4a
extern tramplin_4b
extern tramplin_4c
extern tramplin_4d
extern tramplin_4e
extern tramplin_4f
extern tramplin_50
extern tramplin_51
extern tramplin_52
extern tramplin_53
extern tramplin_54
extern tramplin_55
extern tramplin_56
extern tramplin_57
extern tramplin_58
extern tramplin_59
extern tramplin_5a
extern tramplin_5b
extern tramplin_5c
extern tramplin_5d
extern tramplin_5e
extern tramplin_5f
extern tramplin_60
extern tramplin_61
extern tramplin_62
extern tramplin_63
extern tramplin_64
extern tramplin_65
extern tramplin_66
extern tramplin_67
extern tramplin_68
extern tramplin_69
extern tramplin_6a
extern tramplin_6b
extern tramplin_6c
extern tramplin_6d
extern tramplin_6e
extern tramplin_6f
extern tramplin_70
extern tramplin_71
extern tramplin_72
extern tramplin_73
extern tramplin_74
extern tramplin_75
extern tramplin_76
extern tramplin_77
extern tramplin_78
extern tramplin_79
extern tramplin_7a
extern tramplin_7b
extern tramplin_7c
extern tramplin_7d
extern tramplin_7e
extern tramplin_7f
extern tramplin_80
extern tramplin_81
extern tramplin_82
extern tramplin_83
extern tramplin_84
extern tramplin_85
extern tramplin_86
extern tramplin_87
extern tramplin_88
extern tramplin_89
extern tramplin_8a
extern tramplin_8b
extern tramplin_8c
extern tramplin_8d
extern tramplin_8e
extern tramplin_8f
extern tramplin_90
extern tramplin_91
extern tramplin_92
extern tramplin_93
extern tramplin_94
extern tramplin_95
extern tramplin_96
extern tramplin_97
extern tramplin_98
extern tramplin_99
extern tramplin_9a
extern tramplin_9b
extern tramplin_9c
extern tramplin_9d
extern tramplin_9e
extern tramplin_9f
extern tramplin_a0
extern tramplin_a1
extern tramplin_a2
extern tramplin_a3
extern tramplin_a4
extern tramplin_a5
extern tramplin_a6
extern tramplin_a7
extern tramplin_a8
extern tramplin_a9
extern tramplin_aa
extern tramplin_ab
extern tramplin_ac
extern tramplin_ad
extern tramplin_ae
extern tramplin_af
extern tramplin_b0
extern tramplin_b1
extern tramplin_b2
extern tramplin_b3
extern tramplin_b4
extern tramplin_b5
extern tramplin_b6
extern tramplin_b7
extern tramplin_b8
extern tramplin_b9
extern tramplin_ba
extern tramplin_bb
extern tramplin_bc
extern tramplin_bd
extern tramplin_be
extern tramplin_bf
extern tramplin_c0
extern tramplin_c1
extern tramplin_c2
extern tramplin_c3
extern tramplin_c4
extern tramplin_c5
extern tramplin_c6
extern tramplin_c7
extern tramplin_c8
extern tramplin_c9
extern tramplin_ca
extern tramplin_cb
extern tramplin_cc
extern tramplin_cd
extern tramplin_ce
extern tramplin_cf
extern tramplin_d0
extern tramplin_d1
extern tramplin_d2
extern tramplin_d3
extern tramplin_d4
extern tramplin_d5
extern tramplin_d6
extern tramplin_d7
extern tramplin_d8
extern tramplin_d9
extern tramplin_da
extern tramplin_db
extern tramplin_dc
extern tramplin_dd
extern tramplin_de
extern tramplin_df
extern tramplin_e0
extern tramplin_e1
extern tramplin_e2
extern tramplin_e3
extern tramplin_e4
extern tramplin_e5
extern tramplin_e6
extern tramplin_e7
extern tramplin_e8
extern tramplin_e9
extern tramplin_ea
extern tramplin_eb
extern tramplin_ec
extern tramplin_ed
extern tramplin_ee
extern tramplin_ef
extern tramplin_f0
extern tramplin_f1
extern tramplin_f2
extern tramplin_f3
extern tramplin_f4
extern tramplin_f5
extern tramplin_f6
extern tramplin_f7
extern tramplin_f8
extern tramplin_f9
extern tramplin_fa
extern tramplin_fb
extern tramplin_fc
extern tramplin_fd
extern tramplin_fe
extern tramplin_ff


global init_idt

extern allocate_blocks


; void init_idt();
; initialize interrupt descriptor table in heap
init_idt:
push 4
call allocate_blocks        ; get 2 KiB for idt (256 * 8 bytes per entity)
add esp, 4

mov eax, tramplin_0         ; get addr
mov word [esp + 0], ax      ; low addr bits
mov word [esp + 2], 8       ; offset in gdt
mov byte [esp + 4], 0       ; gap
mov byte [esp + 5], 0x8e    ; interrupt gate
shr eax, 16                 ; get high addr bits
mov word [esp + 6], ax      ; high addr bits
